// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.startupRolloutPrefs.javascript.options.wasm_caching", false);
user_pref("app.normandy.user_id", "542a13b2-b71b-46ba-bd10-a566269451ab");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1651766959);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1651766936);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1651768491);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{b6d05808-56a0-4c76-b691-8a9766f55c9c}");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1651766929);
user_pref("browser.laterrun.bookkeeping.sessionCount", 2);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 125);
user_pref("browser.newtabpage.activity-stream.discoverystream.rec.impressions", "{\"127468\":1651766954862,\"127559\":1651766954867,\"197415819\":1651766954855}");
user_pref("browser.newtabpage.activity-stream.discoverystream.spoc.impressions", "{\"189212196\":[1651766954849,1651768492302]}");
user_pref("browser.newtabpage.activity-stream.impressionId", "{7067de53-7310-40fd-97d4-2f2578325666}");
user_pref("browser.newtabpage.pinned", "[]");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1651766930);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1651766955266");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1651768763266");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1651766937157");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1651788537157");
user_pref("browser.search.region", "US");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20220330194208");
user_pref("browser.startup.couldRestoreSession.count", 2);
user_pref("browser.startup.homepage_override.buildID", "20220330194208");
user_pref("browser.startup.homepage_override.mstone", "99.0");
user_pref("browser.startup.lastColdStartupCheck", 1651768491);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\",\"toolbar-menubar\",\"TabsToolbar\"],\"currentVersion\":17,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("browser.urlbar.quicksuggest.scenario", "offline");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1651766932894");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "99.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "US");
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("dom.push.userAgentID", "10308f80fcc64246a91387a67ed72dfb");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20220330194208");
user_pref("extensions.lastAppVersion", "99.0");
user_pref("extensions.lastPlatformVersion", "99.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"1a9a6f66-64d0-41ab-b75b-f024e6c10a4e\",\"formautofill@mozilla.org\":\"62029cb0-fe68-43e3-a0a7-778d741f2641\",\"pictureinpicture@mozilla.org\":\"a20b54ba-59fd-437e-9117-288d02f4b99a\",\"screenshots@mozilla.org\":\"05c37352-a7ce-4cb8-acfa-18705da2a3d6\",\"webcompat-reporter@mozilla.org\":\"2408b692-5397-44a9-bed0-0580ad7e126d\",\"webcompat@mozilla.org\":\"31030e9f-f038-4dfd-b924-88b90e417684\",\"default-theme@mozilla.org\":\"18f4932a-33fd-4c3b-b726-6780eb353202\",\"addons-search-detection@mozilla.com\":\"eec3e125-5ab6-4a8b-b4d1-49b4c91e0f0d\",\"google@search.mozilla.org\":\"9d00b200-c31d-434b-af16-5a639d0d1a5a\",\"amazondotcom@search.mozilla.org\":\"4271e623-6f4b-4f3b-95c8-e2522db171f4\",\"wikipedia@search.mozilla.org\":\"751eaba5-9b98-4253-96e1-d3353f48c498\",\"bing@search.mozilla.org\":\"1f4092bb-b7e5-4eba-94ee-01833548aa4f\",\"ddg@search.mozilla.org\":\"cf5055fe-7000-4da3-838f-aba7afe969f1\",\"ebay@search.mozilla.org\":\"83e6abbf-9e6f-4c7e-8f18-496f20194057\"}");
user_pref("fission.experiment.max-origins.last-disqualified", 0);
user_pref("fission.experiment.max-origins.last-qualified", 1651766935);
user_pref("fission.experiment.max-origins.qualified", true);
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("permissions.default.geo", 2);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "db003cf0-5ae1-4862-bfaf-a558d68420d4");
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.declinedEngines", "");
user_pref("services.sync.engine.addresses.available", true);
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.nextSync", 0);
user_pref("services.sync.tabs.lastSync", "0");
user_pref("toolkit.startup.last_success", 1651768490);
user_pref("toolkit.telemetry.cachedClientID", "d56bcec6-ce36-4487-8d72-f6e689532f18");
user_pref("toolkit.telemetry.previousBuildID", "20220330194208");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
